name: CI/CD
on:
  push:
    branches: [ main ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: get pwd
        run: pwd
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd src
          pip install -r requirements.txt
          pip install python-dotenv
      - name: Run Tests
        run: |
          cd src
          export AWS_ACCESS_KEY_ID=AKIATK4N722TKS2R7PCK
          export AWS_SECRET_ACCESS_KEY=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
          export AWS_S3_BUCKET=term4-assignment
          export DB_URI=postgresql+psycopg2://postgres:Stephen22968@35.174.208.249:5432/library_api
          python -m unittest discover -s tests/ -v
  deployment:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          #IP address of EC2 instance
          host: 35.174.208.249
          #User you created on the EC2 instance
          username: github-actions
          #Name of the secrets variable where you put your secret key
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            rm -rf Term4_Assignment_real
            sudo apt-get install python3-venv
            git clone https://github.com/mrixon95/Term4_Assignment_real.git
            cd Term4_Assignment_real
            python3 -m venv venv
            source venv/bin/activate
            sudo pip install -r Term4_Assignment/requirements.txt
