name: CI/CD
on:
  push:
    branches: [ main ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: get pwd
        run: pwd
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd src
          pip install -r requirements.txt
          pip install python-dotenv
      - name: Run Tests
        run: |
          cd src
          export FLASK_ENV=deveopment
          export FLASK_APP=main.py

          python -m unittest discover -s tests/ -v
  deployment:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          #IP address of EC2 instance
          host: 35.174.208.249
          #User you created on the EC2 instance
          username: github-actions
          #Name of the secrets variable where you put your secret key
          key: $
          port: 22
          script: |
            rm -rf Term4_Assignment_real
            git clone https://github.com/mrixon95/Term4_Assignment_real.git
            python3.8 -m venv /home/github-actions/Term4_Assignment/venv
            /home/github-actions/Term4_Assignment/venv/bin/pip3.8 install -r /home/github-actions/Term4_Assignment/requirements.txt
